codesandbox/codesandbox-importers

- packages/import-utils/src/create-sandbox/templates.ts
- packages/types/index.d.ts
related: https://github.com/CompuIves/codesandbox-client/pull/1121
> Add Nest SSE template

- packages/import-utils/src/create-sandbox/templates.ts
- packages/types/index.d.ts
Related: https://github.com/CompuIves/codesandbox-client/pull/1113
> Add ember-cli project support

- packages/import-utils/src/create-sandbox/templates.ts
- packages/types/index.d.ts
Prerequisite for https://github.com/CompuIves/codesandbox-client/pull/1265
> Add Styleguidist

- packages/import-utils/src/create-sandbox/templates.ts
You guys rock <3
Yes, nuxt-ts is coming, with full TypeScript support 👀
> Add support for `nuxt-ts`

- packages/import-utils/src/create-sandbox/templates.ts
- packages/types/index.d.ts
Not sure if I need to add this here or if I did this correctly, but opening a PR just in case. Think I'm definitely missing something?
> Add VuePress support

- packages/import-utils/src/create-sandbox/templates.ts
> move tp switch , fix gridsome

- packages/cli/package.json
- yarn.lock
Fixes https://github.com/CompuIves/codesandbox-client/issues/1537 .
> cli: Update inquirer

- packages/cli/README.md
Just like codesandbox/codesandbox-client#1856
> Move to codesandbox org

- packages/import-utils/src/create-sandbox/templates.ts
- packages/types/index.d.ts
Hope this is ok! 😄 
[The codesandbox-client PR is also here.](https://github.com/codesandbox/codesandbox-client/pull/1888) 
Scott
> Imports Quasar

- package.json
- packages/git-extractor/package.json
- packages/git-extractor/src/routes/github/api.ts
- packages/git-extractor/src/routes/github/index.ts
- packages/git-extractor/src/routes/github/pull/download.ts
- packages/git-extractor/src/routes/github/types.d.ts
- packages/import-utils/src/utils/files/denormalize.ts
- packages/types/index.d.ts
- run-docker.sh
- yarn.lock
Now for private sandboxes we return `binaryContent` on the module (base64 contents), the server will upload this and set the right url in the content.
> Allow uploading private binary files

- packages/import-utils/src/create-sandbox/index.ts
- packages/import-utils/src/create-sandbox/templates.ts
If there's no `package.json` we default to the static project
> Allow creating static projects

- packages/import-utils/src/create-sandbox/templates.ts
Hey all 👋 
We need to modify a bit how the importer discover an Adonis project for our next release.
> feat(template): support Adonis V5

- packages/import-utils/src/create-sandbox/utils/resolve.ts
- packages/import-utils/src/utils/files/__tests__/__snapshots__/denormalize.test.ts.snap
- packages/import-utils/src/utils/files/__tests__/denormalize.test.ts
Fixes issue with syncing directories with multiple sub dirs. Probably fixes a lot of other bugs as well!
> traverse all sub dirs

- packages/git-extractor/src/routes/define.test.ts
- packages/git-extractor/src/routes/define.ts
- packages/import-utils/src/create-sandbox/index.ts
- packages/import-utils/tsconfig.json
Fixes https://github.com/codesandbox/codesandbox-client/issues/4983
> Fix inferring the package.json in define calls

- packages/import-utils/src/create-sandbox/templates.ts
- packages/types/index.d.ts
Related: 
https://github.com/codesandbox/codesandbox-client/pull/5343
> Add Docusaurus

- packages/import-utils/src/create-sandbox/templates.ts
Add automatic node support for  [Frontity](https://frontity.org/) projects
> Add Frontity to node

- packages/cli/package.json
- packages/cli/src/utils/api.ts
Fixes warnings when installing as a dependency.
> Upgrades datauri version and usage

- packages/git-extractor/src/routes/github/api.ts
> Forward status of error from GitHub

- packages/git-extractor/src/routes/github/api.ts
- yarn.lock
There was a bug in AppSignal that prevented it from logging the params/query. They've fixed this in a later version.
> Upgrade AppSignal

- packages/git-extractor/src/routes/github/api.ts
> Check if a repo exists before creating it

- Dockerfile.dev
I think this is the correct file? Let me know if it isn't.
> Add zsh & vim to dev dockerfile

- packages/import-utils/src/create-sandbox/templates.ts
Improved: moved remix (and astro) up with server templates
> Add remix detection

- packages/import-utils/src/create-sandbox/templates.ts
> fix: redux example detection
