packages/cli/src/commands/deploy.ts
Problem: `process.cwd()` returns an absolute path on Windows, which breaks downstream processing of files and directories.
Fix: Replace `join(process.cwd(), path);` with `join("./", path);` before reading all files/directories with fs.readDir.
Fixes CompuIves/codesandbox-client#691
=> Fix path scanning for Windows

packages/cli/package.json
Small change so finding the CLI on npm directs you here instead of to the archived repository.
=> Update repository field to new git repository

packages/import-utils/src/create-sandbox/index.ts
Like I said, this is a minimal solution to issue #10. Another approach (but longer) could be making sure all of the paths in `directory` are Unix-like ahead of time, then a platform check wouldn't be neccessary.
If you'd like to have some automated tests for this let me know.
Closes #10
=> Fix main file path error in Windows

packages/import-utils/src/create-sandbox/templates.ts
Dojo is deprecating the use of @dojo/core as it has been merged into a new @dojo/framework package going forward. Add a check for this package to know to use the @dojo/cli-create-app template. This fixes compuives/codesandbox-client#988.
=> add support for Dojo 3+

packages/import-utils/src/create-sandbox/templates.ts
Changed template inference for Apollo, Nuxt and Dojo to use the pattern `totalDependencies.some(dep => <dependenciesList>.includes(dep))` to check against a list of package names, which is the equivalent to multiple OR conditionals.
some() will return true if one or more items in the callback returns true, and includes() will return true if an item exists within an array.
For each template that could match against multiple packages, those packages have been placed in their own list, for example:
```javascript
const nuxt = ["nuxt", "nuxt-edge"]
if (totalDependencies.some(dep => nuxt.includes(dep))) {
return "nuxt";
}
```
Because apollo-server has multiple different packages to support different server frameworks (such as Express, Hapi, Koa, etc), a list has been added for those packages so …
=> Update Template Inference for Apollo, Nuxt, Dojo

packages/cli/src/utils/log.ts, packages/cli/src/utils/parse-sandbox/index.ts
Should fix this issue: https://github.com/codesandbox-app/codesandbox-importers/issues/20
Nine days ago (in v.1.3.2) chalk was changed from `import * chalk from "chalk"` to `import chalk from "chalk"`. After TypeScript transpilation, `chalk` === `undefined`, leading to the dreaded...
**TypeError: Cannot read property 'blue' of undefined**.
=> Fixed chalk import

packages/import-utils/src/create-sandbox/templates.ts
Since `dependencies` & `devDependencies` are optional in `package.json` and they're getting a default value on line 62, this should be reflected in the type of the arguments.
CC: @CompuIves
=> Fix getTemplate types

packages/git-extractor/src/index.ts
Allow importing GitHub commit URLs e.g. `https://codesandbox.io/s/github/excalidraw/excalidraw/commit/dc0a4f4cb8bf85a541a9a1a85c7cf60dfac362c9` . Fixes https://github.com/codesandbox/codesandbox-client/issues/3379 .
=> Allow commit URLs

packages/import-utils/src/create-sandbox/templates.ts
Projects using @tensorflow/tfjs-node require a container.
=> Use Node template when importing a project using tfjs-node

packages/cli/package.json, yarn.lock
The package `codesandbox` has axios@0.16.2 as a dependency, which has a high-level security vulnerability (https://github.com/axios/axios/issues/2164)
This PR upgrades to axios@0.18.1
=> Upgrade to axios 0.18.1

packages/import-utils/src/utils/files/denormalize.ts, packages/types/index.d.ts
We need to expose the `sha` as **GitHub implementation** needs to store new modules using the sha when syncing.
=> expose sha

packages/import-utils/src/create-sandbox/templates.ts
This makes it so every snowpack sandbox is now a node sandbox because we cannot run this in the browser 
Related issue: https://github.com/codesandbox/codesandbox-client/issues/5335
=> if snowpack is installed its a node sandbox

packages/import-utils/src/create-sandbox/templates.ts
Add support for the newer @roxi/routify (which is the old @sveltech/routify) template
=> Support @roxi/routify import

packages/git-extractor/src/routes/github/api.ts
Fixes https://github.com/codesandbox/codesandbox-importers/issues/72 and error often seen in Sentry https://sentry.io/organizations/codesandbox/issues/1958008789/?project=4377691
If a repo has files named with non-English characters, `downloadRepository` fails on `getLatestCommitShaOfFile` and then causes the whole import to fail.
Adding `encodeURI` to the url in at least this one place should fix that 👇  🎉
=> Encode URI for Github API calls to prevent unescaped character errors

packages/git-extractor/src/routes/github/api.ts
much encoding
very handle all characters
wow
(Follow up to https://github.com/codesandbox/codesandbox-importers/pull/119 because we still got unescaped character errors on other paths)
=> Round 2: add encodeURI to all Github API calls

packages/git-extractor/src/routes/github/api.ts
With this, we'll be able to map out aaalll the requests we do to GitHub, in a single graph. This way we'll know for every request whether we're working on the rate limit.
=> Add logging on request kinds to AppSignal

packages/import-utils/src/create-sandbox/templates.ts
Currently, when an Astro project is imported into CodeSandbox, it is interpreted as a React project, and overriding this with "template": "node" is required in a sandbox.config file.
We believe this addition to your import logic should correctly identify Astro on import.
=> Import an Astro project from GitHub as node template

packages/import-utils/src/create-sandbox/index.ts
Pretty sure this is the issue that causes errors on any sandbox that does not contain a `package.json`, but we should verify with some test sandboxes.
=> Fix possible null packageJsonPackage

packages/import-utils/src/create-sandbox/__tests__/templates.test.ts, packages/import-utils/src/create-sandbox/templates.ts
Description:
This pull request aims to enhance the package.json parsing functionality in `codesandbox-importers` to include the detection of create-react-app forks. Currently, `codesandbox-importers` detects only the presence of `react-scripts` in the package.json file but not `@fork/react-scripts` for React applications. So, it does not account for the increasing number of forks that offer extended functionalities, customizations, or tailored setups. Many developers rely on create-react-app forks that cater to specific project requirements or provide additional features. By enhancing the package.json parsing, `codesandbox-importers` can better recognize and accommodate these create-react-app forks, ensuring a seamless and comprehensive experience for developers.
The proposed …
=> Improve package.json Parsing to Detect create-react-app Forks

packages/import-utils/src/create-sandbox/templates.ts
Requested by a maintainer in support because their GH templates need to be cloud sandboxes.
=> Add van-js and mini-van-plate as server dependencies

packages/import-utils/src/create-sandbox/templates.ts
Allows us to set the template using `.codesandbox/template.json`. I've renamed the field to `runtime` as it reflects better what it is today.
=> feat: support setting template using template.json
